server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/magiccook
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false

    mode: HTML5
    encoding: UTF-8
    content-type: text/html


logging:
  level:
    root: info
    org.springframework.security: DEBUG
  path: F:\
  file: magiccook.log

